sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx4d24bda726c3f0c3
    secret: f6523f42fc9e210ef160e00bdfe60ba6